In [4]:
import numpy as np
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
import numpy as np
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [20]:
import numpy as np
a=np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [21]:
import numpy as np
a=np.identity(2)
a

array([[1., 0.],
       [0., 1.]])

In [18]:
a=np.full((2,3),2)
a

array([[2, 2, 2],
       [2, 2, 2]])

In [24]:
np.diag((1,2))

array([[1, 0],
       [0, 2]])

In [27]:
np.random.random(3)

array([0.64422714, 0.57728582, 0.25844165])

In [34]:
np.tile(1,(2,1))

array([[1],
       [1]])

In [36]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [42]:
np.ravel(0,3)

array([0])

In [46]:
a=np.arange(2)
b=a.copy()
b

array([0, 1])

In [51]:
import numpy as np
bb=np.arange(3,7)
bb.max()

6

In [52]:
import numpy as np
bb=np.arange(5)
bb.argmax()

4

In [53]:
bb=np.arange(5)
bb.argmin()

0

In [55]:
bb=np.arange(5)
bb.min()

0

AttributeError: module 'numpy' has no attribute 'len'

In [58]:
import numpy as np
a=np.array([1,2])
a

array([1, 2])

In [3]:
import numpy as np
b=np.arange(1,2)
b

array([1])

In [62]:
np.random.sample(2,3)


TypeError: random_sample() takes at most 1 positional argument (2 given)

In [31]:
np.random.rand(1,2)

array([[0.81862519, 0.74427457]])

In [65]:
import numpy as np
a=np.random.random(3)
print(a)
a.argsort()

[0.7289258  0.30441564 0.77966584]


array([1, 0, 2], dtype=int64)

In [73]:
import numpy as np
a=np.asarray([1,2,3])
a



array([1, 2, 3])

In [76]:
a=np.asfortranarray([[3,4],[5,6]])
a

array([[3, 4],
       [5, 6]])

In [109]:
import numpy as np
np.atleast_1d([1,2])

array([1, 2])

In [108]:
import numpy as np
np.atleast_2d([1,2])

array([[1, 2]])

In [89]:
import numpy as np
np.atleast_3d([1,2])

array([[[1],
        [2]]])

In [93]:
a=([3,2,3,5,6,6,9,8,8])
np.bincount(a)

array([0, 0, 1, 2, 0, 1, 2, 0, 2, 1], dtype=int64)

In [125]:
e=np.array([1,2,3,4])
e

array([1, 2, 3, 4])

In [126]:
f=np.array([5,6,5,7])
f

array([5, 6, 5, 7])

In [99]:
np.row_stack((e,f))

array([[1, 2, 3],
       [5, 6, 7]])

In [100]:
np.column_stack((e,f))

array([[1, 5],
       [2, 6],
       [3, 7]])

In [102]:
np.vstack((e,f))

array([[1, 2, 3],
       [5, 6, 7]])

In [103]:
np.hstack((e,f))

array([1, 2, 3, 5, 6, 7])

In [128]:
d=np.dstack((e,f))
print(d,d.ndim)

[[[1 5]
  [2 6]
  [3 5]
  [4 7]]] 3


In [130]:
print(e,f)
np.convolve(e,f)

[1 2 3 4] [5 6 5 7]


array([ 5, 16, 32, 55, 53, 41, 28])

In [132]:
np.convolve([1,2,3],[0,1,0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [134]:
np.bincount([1,1,2,1,2,3])

array([0, 3, 2, 1], dtype=int64)

In [135]:
np.correlate(e,f)

array([60])

In [137]:
np.concatenate((e,f))

array([1, 2, 3, 4, 5, 6, 5, 7])

In [139]:
np.cumsum((e,f))

array([ 1,  3,  6, 10, 15, 21, 26, 33], dtype=int32)

In [147]:
np.delete(f,e)

c:\users\pravallika\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  """Entry point for launching an IPython kernel.


array([5])

In [154]:
a=np.array([11,22,33,44])
np.delete(2,3)


IndexError: index 3 is out of bounds for axis 0 with size 1

In [166]:
np.ediff1d(f)

array([ 1, -1,  2])

In [168]:
x = np.array([1, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
inds

array([1, 4, 3, 2], dtype=int64)

In [179]:
np.expand_dims(e,axis=0)

array([[1, 2, 3, 4]])

In [189]:
np.extract([1,2],[4,6])

array([4, 6])

In [20]:
import numpy as np
a=np.arange(6).reshape(-3,2)
b=np.full_like(a,3)
b


[[0 1]
 [2 3]
 [4 5]]


array([[3, 3],
       [3, 3],
       [3, 3]])

In [14]:
np.flatten((e,f))

AttributeError: module 'numpy' has no attribute 'flatten'

In [21]:
np.frombuffer(a) 

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313])

In [34]:
np.histogram([2])

(array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64),
 array([1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5]))

In [38]:
np.interp(e,f) 

NameError: name 'e' is not defined

In [44]:
np.ndenumerate([1])

In [50]:
np.ndindex(1,2)

In [54]:
np.nditer([1])

In [60]:
np.partition([1,2,3],axis=0)

TypeError: partition() missing 1 required positional argument: 'kth'

In [66]:
np.ptp([1,50])

49

In [68]:
np.repeat(1,3) 

array([1, 1, 1])

In [83]:
np.roll(1,3)

array(1)

In [87]:
np.roots([1,2])

array([-2.])

In [90]:
np.round_(2.8)

3.0

In [93]:
np.searchsorted(1,2,3)

ValueError: expected nonempty string for keyword 'side'

In [95]:
np.sinc(5)

3.898171832519376e-17

In [97]:
np.sort([1,5,3,0,7,6])

array([0, 1, 3, 5, 6, 7])

In [100]:
np.stack([4,3,4])
#numpy.take() 

array([4, 3, 4])

In [112]:
np.take(a[2]) 

TypeError: take() missing 1 required positional argument: 'indices'

In [116]:
import numpy as np
c=np.array([1,2,3,4])
np.all(c)


True

In [118]:
np.any(c)

True

In [119]:
np.conj(c)
#conjugate()
#cumprod()

array([1, 2, 3, 4], dtype=int32)

In [120]:
np.conjugate(c)

array([1, 2, 3, 4], dtype=int32)

In [121]:
np.cumprod(c)

array([ 1,  2,  6, 24], dtype=int32)

In [131]:
np.nonzero([1,5,8,7,5,6])
#prod()

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [134]:
np.prod([1,2,3])

6

In [135]:
np.take(2)

TypeError: take() missing 1 required positional argument: 'indices'

In [137]:
np.percentile(c,2)

1.06