In [54]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([9,8,7,6])
print(a+b,a-b,a*b,a/b,a^b,a%b,a//b)
print(a.dtype)

[10 10 10 10] [-8 -6 -4 -2] [ 9 16 21 24] [0.11111111 0.25       0.42857143 0.66666667] [ 8 10  4  2] [1 2 3 4] [0 0 0 0]
int32


In [52]:
import numpy as np
a=np.array([1,2])
b=np.array([9,8])
print(a+b,a-b,a*b,a/b,a^b,a%b,a//b)

[10 10] [-8 -6] [ 9 16] [0.11111111 0.25      ] [ 8 10] [1 2] [0 0]


In [4]:
#np? we will get inbuit methods

In [9]:
print(np.sin(a),np.cos(a),np.max(a))



[ 0.84147098  0.90929743  0.14112001 -0.7568025 ] [ 0.54030231 -0.41614684 -0.9899925  -0.65364362] 4


In [1]:
for a not in list(range(10,20)):
    print(a)
#not in cannot be used in loop but we can use in conditional statements

SyntaxError: invalid syntax (<ipython-input-1-7ebf274e83ff>, line 1)

In [2]:
l=[1,2,3]
2 in l

True

In [ ]:
Vector=1 dimension array
matrix=2 dimensional array

In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.size,a.ndim,a.shape)

6 2 (2, 3)


In [ ]:
data types in arrays
np.unint8
np.int64
np.

In [12]:
import numpy as np
np.zeros((100,100),dtype=np.uint8)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
import numpy as np
np.ones(2,5)

In [ ]:
#define 4*4 matrix and perform all arthimatic operations


In [4]:
import numpy as np
a=np.array([1,2,3])
a.shape,a.size,a.ndim

((3,), 3, 1)

In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[5,7,9]],dtype=np.float32)
a.shape,a.size,a.ndim

((3, 3), 9, 2)

In [12]:
#list=vector(only rows)
#nestedlist=matrix(combiantion of rows and coloumns)

In [14]:
import numpy as np
d=np.zeros((10,10),dtype=float)
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
import numpy as np
d=np.zeros((10,10),dtype=np.float32)
print(d,id(d))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 2677249900016


In [18]:
import numpy as np
d=np.zeros((10,10),dtype=complex)
d

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [21]:
import numpy as np
d=np.zeros((10,10),dtype=np.complex128)
d

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [23]:
import numpy as np
d=np.arange(0,100,5)
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [24]:
import numpy as np
d=np.arange(1,100,2)
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [25]:
#int64,float32,complex,bool(numpy data types)

In [29]:
import numpy as np
a=np.ones((2,3))
b=np.zeros((4,3))
np.concatenate([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
import numpy as np
a=np.ones((2,3))
b=np.zeros((4,3))
np.concatenate(([a,b]),axis=0)#axis1 means rows shud be same,axis0 means columns shud be same


array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
import numpy as np
a=np.ones((2,3))
b=np.zeros((4,3))
np.concatenate(([a,b]),axis=0)
print(a.astype(np.float32))

[[1. 1. 1.]
 [1. 1. 1.]]


In [50]:
import numpy as np
a=np.ones((2,3))
b=np.ones((2,3))
np.concatenate(([a,b]))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
import numpy as np
a=np.ones((2,2))
a=np.full_like(8)
a


TypeError: full_like() missing 1 required positional argument: 'fill_value'

In [39]:
a=np.zeros((2,2))
b=np.empty_like(a)
b

array([[0., 0.],
       [0., 0.]])

In [46]:
import numpy as np
a=np.ones((2,2,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
import numpy as np
a=np.ones((2,2,1))
a

array([[[1.],
        [1.]],

       [[1.],
        [1.]]])

In [49]:
import numpy as np
a=np.ones((2,2,10))
a

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [66]:
import numpy as np
np.random.random((2,2))
#random means it will print

array([[0.57553475, 0.15853968],
       [0.81311896, 0.61964619]])

In [26]:
import numpy as np
np.random.random((2,2))

array([[0.46216102, 0.25247898],
       [0.54420292, 0.07408059]])

In [32]:
import numpy as np
np.random.randint(3)

2

In [68]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
import numpy as np
np.empty((2,2))

array([[1.64029794e-321, 1.06811015e-306],
       [1.24611470e-306, 9.80720103e-312]])

In [5]:
import numpy as np
x=np.array(np.arange(12))
x.reshape(3,4)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
import numpy as np
x=np.matrix(np.arange(12))
x.reshape(3,4)
x

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [3]:
import numpy as np
x=np.matrix(np.arange(12))
x.reshape(3,4)
x

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [23]:
import numpy as np
ad=np.ravel(np.arange(3))
nd=ad.copy()
nd

array([0, 1, 2])

In [7]:
x.reshape(6,-2)

matrix([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [9]:
x.ravel()

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [10]:
a=np.copy(x)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [18]:
import numpy as np
b=np.arange(3).reshape(3,1)
print(b.T,b.ndim)



[[0 1 2]] 2


In [16]:
b.transpose(1,0)

array([[0, 1, 2]])

In [13]:
b.transpose(0,1)#1column multi rows

array([[0],
       [1],
       [2]])

In [39]:
list1=list(range(2000))
list1

TypeError: 'list' object is not callable

In [41]:
import numpy as np
a=np.zeros((100,100,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
a[:,:,0]=3
a

array([[[3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.],
        ...,
        [3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.]],

       [[3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.],
        ...,
        [3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.]],

       [[3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.],
        ...,
        [3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.]],

       ...,

       [[3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.],
        ...,
        [3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.]],

       [[3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.],
        ...,
        [3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.]],

       [[3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.],
        ...,
        [3., 0., 0.],
        [3., 0., 0.],
        [3., 0., 0.]]])

In [47]:
a[:,:,2]=5
a

array([[[3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.],
        ...,
        [3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.]],

       [[3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.],
        ...,
        [3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.]],

       [[3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.],
        ...,
        [3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.]],

       ...,

       [[3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.],
        ...,
        [3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.]],

       [[3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.],
        ...,
        [3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.]],

       [[3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.],
        ...,
        [3., 0., 5.],
        [3., 0., 5.],
        [3., 0., 5.]]])

In [19]:
import numpy as np
a=np.arange(0,10)
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [21]:
np.sqrt(4)

2.0

In [13]:
import numpy as np
a=np.arange(0,10)
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
import numpy as np
c= np.arange(20)
c.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
a=np.array([10,20,30,40,50,60],dtype=float)#matplot is datavisualization pakage plot is geographical area
